config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'about_contacts/about'
  get 'about_contacts/contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: [:index, :show] do
    collection do
      get 'onSale'
      get 'new'
      get 'search'
    end
  end

  resources :categories, only: [:index, :show]

  resources :cart, only: [:create, :destroy]

  root to: 'home#index'
end

app/models/about_contact.rb
class AboutContact < ApplicationRecord
  validates :aboutTitle, :aboutText, :contactNumber, :contactEmail, :contactTitle, :contactText, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, :dependent => :destroy

  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  has_many :orders, :dependent => :destroy

  validates :name, :email, :address, :postalCode, presence: true
  validates :postalCode, length: { is: 6 }
  validates :email, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  #has_and_belongs_to_many :order_products, :dependent => :destroy

  validates :orderDate, :subTotal, :total, :status, :gstAmount, :pstAmount, presence: true
  validates :subTotal, :total, :gstAmount, :pstAmount, numericality: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :order_product
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  #has_and_belongs_to_many :orders, :dependent => :destroy

  validates :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_products, :dependent => :destroy

  validates :name, :description, :price, presence: true
  validates :price,  numericality: true

  has_one_attached :image
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :Customers, :dependent => :destroy

  validates :name, :gstRate, :pstRate, presence: true
  validates :gstRate, :pstRate, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_session
  helper_method :cart

  private

    def initialize_session
      session[:shopping_cart] ||= []
    end

    def cart
      Product.find(session[:shopping_cart])
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    id = params[:id].to_i
    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id
      product = Product.find(id)
      flash[:notice] = "#{product.name} added to cart!"
      redirect_to root_path
    end
  end

  def destroy
    id = params[:id].to_i
    product = Product.find(id)
    session[:shopping_cart].delete(id)
    flash[:notice] = "#{product.name} removed from cart!"
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:products).page(params[:page])
  end

  def show
    @category = Category.find(params[:id])
    @products = Product.where(category_id: params[:id]).page(params[:page])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @new = Product.includes(:category).where("created_at > ?", 3.days.ago).limit(5)

    @sale = Product.includes(:category).where(onSale: [true, nil]).limit(5)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(:category).page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def onSale
    @products = Product.includes(:category).where(onSale: [true, nil]).page(params[:page])
  end

  def new
    @products = Product.includes(:category).where("created_at > ?", 3.days.ago).page(params[:page])
  end

  def search
    search = "%#{params[:keywords]}%"
    dropdown = "#{params[:category]}"
    category = Category.where("name LIKE ?", dropdown)

    if(dropdown == "All Categories")
      @products = Product.includes(:category).where("name LIKE (?) OR description LIKE (?)", search, search).page(params[:page])
    else
      @products = Product.includes(:category).where("name LIKE (?) OR description LIKE (?)", search, search).where(category_id: category.ids).page(params[:page])
    end
  end
end

app/helpers/about_contacts_helper.rb
module AboutContactsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>New Products!</h1>
<% @new.each do |pro| %>
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-96x96">
       <% !if pro.image.attached? %>
          <%= image_tag pro.image %>
        <% else %>
          <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
        <% end %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= link_to pro.name, pro %></strong>
          <br>
          $<%= pro.price%>
        </p>
      </div>
      <div class="content">
      <% if cart.include?(pro)%>
        <%= button_to cart_path(pro),  class:"button is-info" ,method: :delete do %>
          Remove From Cart
        <% end %>
      <% else %>
        <%= form_with url: cart_index_path, method: :post do%>
          <%= hidden_field_tag(:id, pro.id)%>
          <%= button_tag "Add To Cart", class: "button is-info" %>
        <% end %>
      <% end %>
      </div>
    </div>
  </article>
</div>
<% end %>
<h1>Big Sale!</h1>
<% @sale.each do |product| %>
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-96x96">
       <% !if product.image.attached? %>
          <%= image_tag product.image %>
        <% else %>
          <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
        <% end %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= link_to product.name, product %></strong>
          <br>
          $<%= product.price%>
        </p>
      </div>
      <div class="content">
      <% if cart.include?(product)%>
        <%= button_to cart_path(product), class:"button is-info" ,method: :delete do %>
          Remove From Cart
        <% end %>
      <% else %>
        <%= form_with url: cart_index_path, method: :post do%>
          <%= hidden_field_tag(:id, product.id)%>
          <%= button_tag "Add To Cart", class: "button is-info" %>
        <% end %>
      <% end %>
      </div>
    </div>
  </article>
</div>
<% end %>