config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'about_contacts/about'
  get 'about_contacts/contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: [:index, :show] do
    collection do
      get 'onSale'
      get 'new'
      get 'search'
    end
  end

  resources :categories, only: [:index, :show]

  resources :cart, only: [:create, :destroy]

  root to: 'home#index'
end

app/models/about_contact.rb
class AboutContact < ApplicationRecord
  validates :aboutTitle, :aboutText, :contactNumber, :contactEmail, :contactTitle, :contactText, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, :dependent => :destroy

  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  has_many :orders, :dependent => :destroy

  validates :name, :email, :address, :postalCode, presence: true
  validates :postalCode, length: { is: 6 }
  validates :email, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  #has_and_belongs_to_many :order_products, :dependent => :destroy

  validates :orderDate, :subTotal, :total, :status, :gstAmount, :pstAmount, presence: true
  validates :subTotal, :total, :gstAmount, :pstAmount, numericality: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :order_product
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  #has_and_belongs_to_many :orders, :dependent => :destroy

  validates :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_products, :dependent => :destroy

  validates :name, :description, :price, presence: true
  validates :price,  numericality: true

  has_one_attached :image
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :Customers, :dependent => :destroy

  validates :name, :gstRate, :pstRate, presence: true
  validates :gstRate, :pstRate, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    id = params[:id].to_i
    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id
      product = Product.find(id)
      flash[:notice] = "#{product.name} added to cart!"
      redirect_to root_path
    end
  end

  def destroy
    id = params[:id].to_i
    product = Product.find(id)
    session[:shopping_cart].delete(id)
    flash[:notice] = "#{product.name} removed from cart!"
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @new = Product.includes(:category).where("created_at > ?", 3.days.ago).limit(5)

    @sale = Product.includes(:category).where(onSale: [true, nil]).limit(5)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(:category).page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def onSale
    @products = Product.includes(:category).where(onSale: [true, nil]).page(params[:page])
  end

  def new
    @products = Product.includes(:category).where("created_at > ?", 3.days.ago).page(params[:page])
  end

  def search
    search = "%#{params[:keywords]}%"
    dropdown = "#{params[:category]}"
    category = Category.where("name LIKE ?", dropdown)

    if(dropdown == "All Categories")
      @products = Product.includes(:category).where("name LIKE (?) OR description LIKE (?)", search, search).page(params[:page])
    else
      @products = Product.includes(:category).where("name LIKE (?) OR description LIKE (?)", search, search).where(category_id: category.ids).page(params[:page])
    end
  end
end

app/helpers/about_contacts_helper.rb
module AboutContactsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TripleSOutfitters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= javascript_pack_tag 'navbar_overflow' %>
<nav class="navbar mb-2" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      Home
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

      <a class="navbar-item" href="/products">
        Products
      </a>

      <a class="navbar-item" href="/categories">
        Categories
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href="/products/onSale">
            Sale
          </a>
          <a class="navbar-item" href="/products/new">
            New Products
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="/about_contacts/about">
            About
          </a>
          <a class="navbar-item" href="/about_contacts/contact">
            Contact
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Cart
          <% if cart.present? %>
            <sup><%= cart.size %></sup>
          <% end %>
        </a>
        <div class="navbar-dropdown">
          <% cart.each do |product| %>
            <a class="navbar-item">
              <%= product.name %> <%= link_to "❌", cart_path(product), method: :delete %>
            </a>
          <% end %>
        </div>
      </div>
      <div class="navbar-item">
        <% if user_signed_in? %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-item' %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-item'  %>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-item'  %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
        <%= form_with(url: search_products_path, method: :get, local: true) do %>
          <div class="field is-grouped mb-4">
            <div class="control">
              <div class="select">
                <%= select_tag "category", raw("<option>All Categories</option><option>Shelters</option><option>Augers</option><option>Heaters</option><option>Electronics</option><option>Ice Rods</option>") %>
              </div>
            </div>
            <div class="control is-expanded">
              <%= text_field_tag(:keywords, nil, class: "input", placeholder: "Search For Products") %>
            </div>
            <div class="control">
              <%= submit_tag("Search", class: "button is-info") %>
            </div>
        </div>
      <% end %>

      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

    <%= yield %>
  </body>
</html>